import { PrismaClient } from '@prisma/client'
import { hash } from 'bcryptjs'

const prisma = new PrismaClient()

function parseDate(dateStr: string): Date | null {
  if (!dateStr || dateStr.trim() === '') return null
  const parts = dateStr.split('/')
  if (parts.length !== 3) return null
  const [month, day, year] = parts
  return new Date(parseInt(year), parseInt(month) - 1, parseInt(day))
}

async function main() {
  console.log('Seeding database...')

  const password = await hash('password123', 12)
  const johnPassword = await hash('risa@2026', 12)

  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: 'alex@example.com' },
      update: {},
      create: { name: 'Alex Brown', email: 'alex@example.com', password },
    }),
    prisma.user.upsert({
      where: { email: 'jane@example.com' },
      update: {},
      create: { name: 'Jane Smith', email: 'jane@example.com', password },
    }),
    prisma.user.upsert({
      where: { email: 'sarah@example.com' },
      update: {},
      create: { name: 'Sarah Williams', email: 'sarah@example.com', password },
    }),
    prisma.user.upsert({
      where: { email: 'mike@example.com' },
      update: {},
      create: { name: 'Mike Johnson', email: 'mike@example.com', password },
    }),
    prisma.user.upsert({
      where: { email: 'john@example.com' },
      update: {},
      create: { name: 'John Doe', email: 'john@example.com', password },
    }),
    prisma.user.upsert({
      where: { email: 'john@risalabs.ai' },
      update: { password: johnPassword },
      create: { name: 'John Doe', email: 'john@risalabs.ai', password: johnPassword },
    }),
  ])

  console.log('Created users:', users.map(u => u.name))

  await prisma.claim.deleteMany()

  // ─── 3 PAID CLAIMS ────────────────────────────────────────────────────────────
  // Fully adjudicated and paid; complete payment details on file.
  // CPT codes are standard oncology / hematology visit codes.

  const claimsData = [

    // PAID #1 — Chemotherapy infusion visit, BCBS primary paid in full
    {
      mrn: '104821',
      patientFirstName: 'James',
      patientLastName: 'Thornton',
      dateOfBirth: '05/12/1958',
      providerFirstName: 'Dr. Sarah',
      providerLastName: 'Chen',
      providerNpi: '1437829054',
      primaryInsurance: 'Blue Cross Blue Shield',
      primaryMemberId: 'BCB7823941',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'BCB043281',
      dateOfService: '01/08/2026',
      chargeAmount: 4850.00,
      claimReceivedDate: '01/10/2026',
      claimNumber: '2026010800142',
      claimStatus: 'PAID',
      checkNumber: '88712345',
      checkDate: '01/28/2026',
      paidAmount: 3880.00,
      paidDate: '01/28/2026',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'Patient responsibility: $970.00 (deductible applied). CPT 96413, 96415, 99214, 85025.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // PAID #2 — Medicare primary + UHC supplement, multi-drug infusion, fully resolved
    {
      mrn: '287634',
      patientFirstName: 'Dorothy',
      patientLastName: 'Hartman',
      dateOfBirth: '08/22/1952',
      providerFirstName: 'Dr. Michael',
      providerLastName: 'Torres',
      providerNpi: '1567234891',
      primaryInsurance: 'Medicare',
      primaryMemberId: '1EG4TE5MK72',
      secondaryInsurance: 'United Healthcare',
      secondaryMemberId: 'UHC9087234',
      claimId: 'MCR712045',
      dateOfService: '12/15/2025',
      chargeAmount: 12740.00,
      claimReceivedDate: '12/18/2025',
      claimNumber: '2025121500899',
      claimStatus: 'PAID',
      checkNumber: '77294810',
      checkDate: '01/06/2026',
      paidAmount: 10192.00,
      paidDate: '01/06/2026',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'Medicare paid 80% of approved amount ($10,192.00). Patient responsibility: $2,548.00 crossover to UHC supplement.',
      stage: 'PROCESSED',
      secondaryClaimNumber: '20251215S0071',
      secondaryClaimReceivedDate: '01/08/2026',
      secondaryClaimStatus: 'PAID',
      secondaryCheckNumber: 'UHC-44129870',
      secondaryCheckDate: '01/22/2026',
      secondaryPaidAmount: 2548.00,
      secondaryPaidDate: '01/22/2026',
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // PAID #3 — Aetna, outpatient oncology E&M + infusion, paid within 21 days
    {
      mrn: '356109',
      patientFirstName: 'George',
      patientLastName: 'Whitfield',
      dateOfBirth: '03/04/1964',
      providerFirstName: 'Dr. Amanda',
      providerLastName: 'Rodriguez',
      providerNpi: '1809345672',
      primaryInsurance: 'Aetna',
      primaryMemberId: 'AET4523901',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'AET309741',
      dateOfService: '01/14/2026',
      chargeAmount: 6215.00,
      claimReceivedDate: '01/16/2026',
      claimNumber: '2026011400317',
      claimStatus: 'PAID',
      checkNumber: '55612389',
      checkDate: '02/04/2026',
      paidAmount: 4972.00,
      paidDate: '02/04/2026',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'Allowed amount: $4,972.00. Patient coinsurance 20% ($993.40) applied to EOB. CPT 99215, 96413, 96415, J9355.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // ─── 2 PARTIALLY PAID CLAIMS ─────────────────────────────────────────────────
    // Primary paid for some CPT codes; remaining line items denied.

    // PARTIALLY PAID #1 — Aetna, CO-97 bundling: infusion CPTs paid, E&M denied same-day
    {
      mrn: '391045',
      patientFirstName: 'Linda',
      patientLastName: 'Castillo',
      dateOfBirth: '07/19/1965',
      providerFirstName: 'Dr. Angela',
      providerLastName: 'Moore',
      providerNpi: '1548237901',
      primaryInsurance: 'Aetna',
      primaryMemberId: 'AET5518279',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'AET447829',
      dateOfService: '01/20/2026',
      chargeAmount: 7320.00,
      claimReceivedDate: '01/22/2026',
      claimNumber: '2026012000447',
      claimStatus: 'PARTIALLY_PAID',
      checkNumber: 'AET-EFT-78321',
      checkDate: '02/10/2026',
      paidAmount: 5124.00,
      paidDate: '02/10/2026',
      deniedCode: 'CO-97',
      denialDate: '02/10/2026',
      denialDescription: 'The benefit for CPT 99215 is included in the payment/allowance for another service that has already been adjudicated. E&M visit billed same day as infusion without modifier 25.',
      deniedLineItems: '99215',
      remarks: 'Aetna paid $5,124.00 (EFT #AET-EFT-78321) for CPT codes 96413, 96415, J9355 (infusion services). E&M visit 99215 denied CO-97 — per NCCI bundling policy, E&M billed same day as infusion requires modifier 25 to be separately reimbursable. Paid CPTs: 96413, 96415, J9355.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // PARTIALLY PAID #2 — UHC, CO-50 medical necessity: E&M + first infusion hour paid,
    //                      additional infusion hours and drug denied as not medically necessary
    {
      mrn: '468312',
      patientFirstName: 'Robert',
      patientLastName: 'Vasquez',
      dateOfBirth: '03/11/1958',
      providerFirstName: 'Dr. Kevin',
      providerLastName: 'Patel',
      providerNpi: '1672938405',
      primaryInsurance: 'United Healthcare',
      primaryMemberId: 'UHC2291047',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'UHC883041',
      dateOfService: '02/03/2026',
      chargeAmount: 9850.00,
      claimReceivedDate: '02/05/2026',
      claimNumber: '2026020300883',
      claimStatus: 'PARTIALLY_PAID',
      checkNumber: 'UHC-EFT-91204',
      checkDate: '02/26/2026',
      paidAmount: 2480.00,
      paidDate: '02/26/2026',
      deniedCode: 'CO-50',
      denialDate: '02/26/2026',
      denialDescription: 'These are non-covered services because this is not deemed a medical necessity by the payer. Additional infusion hours and drug J9355 were not pre-authorized and do not meet UHC clinical criteria for this diagnosis.',
      deniedLineItems: '96415, 96417, J9355',
      remarks: 'UHC paid $2,480.00 (EFT #UHC-EFT-91204) for CPT codes 99215 and 96413. Additional infusion hours 96415, 96417 and drug J9355 denied CO-50 — not medically necessary; pre-authorization not on file for extended infusion duration or this drug regimen. Paid CPTs: 99215, 96413.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // ─── 3 DENIED CLAIMS — ELIGIBILITY DENIAL CATEGORY ONLY ─────────────────────
    // All three denied for eligibility reasons. Each has a distinct root cause
    // so the demo shows different rule engine outcomes.

    // DENIED #1 — CO-27: Coverage terminated before DOS (policy expired 12/31/2025,
    //             service rendered 01/06/2026 under lapsed plan)
    {
      mrn: '419278',
      patientFirstName: 'Margaret',
      patientLastName: 'Sullivan',
      dateOfBirth: '11/30/1960',
      providerFirstName: 'Dr. James',
      providerLastName: 'Park',
      providerNpi: '1923847561',
      primaryInsurance: 'United Healthcare',
      primaryMemberId: 'UHC8834721',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'UHC583924',
      dateOfService: '01/06/2026',
      chargeAmount: 8945.00,
      claimReceivedDate: '01/09/2026',
      claimNumber: '2026010600583',
      claimStatus: 'DENIED',
      checkNumber: '',
      checkDate: '',
      paidAmount: 0,
      paidDate: '',
      deniedCode: 'CO-27',
      denialDate: '01/23/2026',
      denialDescription: 'Expenses incurred after coverage terminated. Member not eligible for benefits.',
      deniedLineItems: '99215, 96413, 96415',
      remarks: 'Eligibility Denial – CO-27. Verify retroactive enrollment or alternative coverage. Contact UHC eligibility hotline: 1-866-892-8006.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // DENIED #2 — CO-28: Coverage not in effect (member ID not found active in plan
    //             on DOS; patient may have switched plans during open enrollment)
    {
      mrn: '532847',
      patientFirstName: 'Thomas',
      patientLastName: 'Reeves',
      dateOfBirth: '06/18/1955',
      providerFirstName: 'Dr. Jennifer',
      providerLastName: 'Kim',
      providerNpi: '1745823016',
      primaryInsurance: 'Cigna',
      primaryMemberId: 'CIG7734921',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'CGN741052',
      dateOfService: '12/20/2025',
      chargeAmount: 5620.00,
      claimReceivedDate: '12/22/2025',
      claimNumber: '2025122000741',
      claimStatus: 'DENIED',
      checkNumber: '',
      checkDate: '',
      paidAmount: 0,
      paidDate: '',
      deniedCode: 'CO-28',
      denialDate: '01/05/2026',
      denialDescription: 'Coverage not in effect at the time the service was provided.',
      deniedLineItems: '99214, 96365, 85025, 80053',
      remarks: 'Eligibility Denial – CO-28. Member may have transitioned to new plan during open enrollment. Obtain updated insurance card and re-verify eligibility via Cigna portal.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // DENIED #3 — CO-22 / N104: Coordination of Benefits eligibility denial.
    //             Medicare is the correct primary payer. Claim was submitted to
    //             BCBS (secondary) without Medicare EOB — BCBS denied CO-22.
    {
      mrn: '671493',
      patientFirstName: 'Patricia',
      patientLastName: 'Nguyen',
      dateOfBirth: '04/25/1967',
      providerFirstName: 'Dr. Robert',
      providerLastName: 'Kim',
      providerNpi: '1612938475',
      primaryInsurance: 'Medicare',
      primaryMemberId: '2MX7HN9QT41',
      secondaryInsurance: 'Blue Cross Blue Shield',
      secondaryMemberId: 'BCB4410923',
      claimId: 'MCR429013',
      dateOfService: '12/11/2025',
      chargeAmount: 3380.00,
      claimReceivedDate: '12/13/2025',
      claimNumber: '2025121100429',
      claimStatus: 'DENIED',
      checkNumber: 'MCR-EFT-44821',
      checkDate: '01/10/2026',
      paidAmount: 1800.00,
      paidDate: '01/10/2026',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'Medicare (primary) adjudicated and paid $1,800 on 01/10/2026 (EFT #MCR-EFT-44821). BCBS secondary claim submitted without Medicare EOMB attached — BCBS denied CO-22 (N104). Resubmit BCBS claim with Medicare EOMB to complete secondary adjudication.',
      stage: 'PROCESSED',
      secondaryClaimNumber: '20251211B0429',
      secondaryClaimReceivedDate: '12/14/2025',
      secondaryClaimStatus: 'DENIED',
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: 'CO-22',
      secondaryDenialDescription: 'This care may be covered by another payer per coordination of benefits.',
      secondaryDeniedLineItems: '99213, 96401, 85730',
    },

    // ─── 2 CODING DENIAL CLAIMS ──────────────────────────────────────────────────
    // Denied due to coding errors: wrong modifier or diagnosis-procedure mismatch.
    // Each triggers the full 14-rule Coding Denial engine.

    // CODING DENIAL #1 — CO-4: Modifier mismatch — modifier -57 appended to 99213
    //                    instead of required modifier -25 for same-day E&M + infusion
    {
      mrn: '584921',
      patientFirstName: 'Jeremy',
      patientLastName: 'Wade',
      dateOfBirth: '05/22/1964',
      providerFirstName: 'Dr. Rachel',
      providerLastName: 'Lee',
      providerNpi: '1847293056',
      primaryInsurance: 'Cigna',
      primaryMemberId: 'CIG7723891',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'CIG553891',
      dateOfService: '02/14/2026',
      chargeAmount: 6840.00,
      claimReceivedDate: '02/16/2026',
      claimNumber: '2026021400553',
      claimStatus: 'DENIED',
      checkNumber: null,
      checkDate: null,
      paidAmount: 0,
      paidDate: null,
      deniedCode: 'CO-4',
      denialDate: '03/05/2026',
      denialDescription: 'The service is inconsistent with the modifier billed.',
      deniedLineItems: '99213, 96413, 96415',
      remarks: 'Cigna denied claim CO-4 — modifier -57 was appended to CPT 99213 (E&M). Modifier -57 is reserved for E&M visits resulting in the decision to perform a major surgical procedure the same or next day. For same-day E&M with infusion (96413, 96415), modifier -25 is required. Full claim denied pending corrected resubmission with modifier -25 on CPT 99213.',
      stage: 'PENDING_VALIDATION',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // CODING DENIAL #2 — CO-11: Diagnosis inconsistent with procedure —
    //                    Z79.899 (long-term drug therapy) does not support
    //                    chemotherapy infusion or trastuzumab (J9355) per LCD L34587
    {
      mrn: '637452',
      patientFirstName: 'Dorothy',
      patientLastName: 'Kim',
      dateOfBirth: '08/17/1967',
      providerFirstName: 'Dr. James',
      providerLastName: 'Parker',
      providerNpi: '1965748302',
      primaryInsurance: 'Blue Cross Blue Shield',
      primaryMemberId: 'BCBS4492037',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'BCBS774312',
      dateOfService: '02/28/2026',
      chargeAmount: 9340.00,
      claimReceivedDate: '03/02/2026',
      claimNumber: '2026022800774',
      claimStatus: 'DENIED',
      checkNumber: null,
      checkDate: null,
      paidAmount: 0,
      paidDate: null,
      deniedCode: 'CO-11',
      denialDate: '03/18/2026',
      denialDescription: 'The diagnosis is inconsistent with the procedure.',
      deniedLineItems: '96413, 96415, J9355',
      remarks: 'BCBS denied CO-11 — primary diagnosis Z79.899 does not support chemotherapy infusion (96413, 96415) or trastuzumab (J9355) per LCD L34587. An active oncologic diagnosis with appropriate ICD-10 specificity (4th–7th character) is required. Resubmit with correct primary diagnosis (e.g., C50.911 — HER2+ right breast cancer) supported by pathology report and oncology treatment records.',
      stage: 'PROCESSED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // ─── 3 IN-PROCESS CLAIMS ─────────────────────────────────────────────────────
    // Claims submitted and received by the payer, currently pending adjudication.
    // No payment or denial details available yet.

    // IN-PROCESS #1 — Medicare, complex infusion visit, recently submitted
    {
      mrn: '782314',
      patientFirstName: 'Richard',
      patientLastName: 'Chambers',
      dateOfBirth: '09/14/1962',
      providerFirstName: 'Dr. Lisa',
      providerLastName: 'Chang',
      providerNpi: '1834729045',
      primaryInsurance: 'Medicare',
      primaryMemberId: '4TY7WE3LM29',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'MCR567028',
      dateOfService: '02/10/2026',
      chargeAmount: 9125.00,
      claimReceivedDate: '02/12/2026',
      claimNumber: '2026021000567',
      claimStatus: 'IN_PROCESS',
      checkNumber: '',
      checkDate: '',
      paidAmount: 0,
      paidDate: '',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'Claim submitted electronically via EDI 837P. Payer acknowledgment received 02/12/2026. Expected adjudication within 14–30 days per Medicare timelines.',
      stage: 'PENDING_VALIDATION',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // IN-PROCESS #2 — Aetna, validated in portal, awaiting EFT
    {
      mrn: '845267',
      patientFirstName: 'Carol',
      patientLastName: 'Bennett',
      dateOfBirth: '12/03/1959',
      providerFirstName: 'Dr. David',
      providerLastName: 'Park',
      providerNpi: '1956472830',
      primaryInsurance: 'Aetna',
      primaryMemberId: 'AET8823047',
      secondaryInsurance: null,
      secondaryMemberId: null,
      claimId: 'AET389402',
      dateOfService: '02/05/2026',
      chargeAmount: 7450.00,
      claimReceivedDate: '02/07/2026',
      claimNumber: '2026020500389',
      claimStatus: 'IN_PROCESS',
      checkNumber: '',
      checkDate: '',
      paidAmount: 0,
      paidDate: '',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'Verified on Aetna provider portal 02/14/2026: claim in "Processing" status. Approved amount pending EFT release. Estimated payment 02/28/2026.',
      stage: 'VALIDATED',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },

    // IN-PROCESS #3 — UHC primary + Cigna secondary, high-charge infusion, pending
    {
      mrn: '923718',
      patientFirstName: 'Frank',
      patientLastName: 'Morrison',
      dateOfBirth: '07/28/1953',
      providerFirstName: 'Dr. Emily',
      providerLastName: 'Watson',
      providerNpi: '1723845901',
      primaryInsurance: 'United Healthcare',
      primaryMemberId: 'UHC5521893',
      secondaryInsurance: 'Cigna',
      secondaryMemberId: 'CIG3890127',
      claimId: 'UHC712083',
      dateOfService: '02/18/2026',
      chargeAmount: 11340.00,
      claimReceivedDate: '02/20/2026',
      claimNumber: '2026021800712',
      claimStatus: 'IN_PROCESS',
      checkNumber: '',
      checkDate: '',
      paidAmount: 0,
      paidDate: '',
      deniedCode: '',
      denialDescription: '',
      deniedLineItems: '',
      remarks: 'High-dollar claim flagged for UHC clinical review. Pre-authorization on file (PA# UHC-2026-88341). Awaiting medical necessity determination. Secondary Cigna claim to be filed after primary adjudication.',
      stage: 'PENDING_VALIDATION',
      secondaryClaimNumber: null,
      secondaryClaimReceivedDate: null,
      secondaryClaimStatus: null,
      secondaryCheckNumber: null,
      secondaryCheckDate: null,
      secondaryPaidAmount: 0,
      secondaryPaidDate: null,
      secondaryDeniedCode: null,
      secondaryDenialDescription: null,
      secondaryDeniedLineItems: null,
    },
  ]

  for (let i = 0; i < claimsData.length; i++) {
    const claim = claimsData[i]
    const assignedUser = users[i % users.length]

    await prisma.claim.create({
      data: {
        mrn: claim.mrn,
        patientFirstName: claim.patientFirstName,
        patientLastName: claim.patientLastName,
        dateOfBirth: parseDate(claim.dateOfBirth)!,
        providerFirstName: claim.providerFirstName,
        providerLastName: claim.providerLastName,
        providerNpi: claim.providerNpi,
        primaryInsurance: claim.primaryInsurance,
        dateOfService: parseDate(claim.dateOfService)!,
        primaryMemberId: claim.primaryMemberId,
        secondaryInsurance: claim.secondaryInsurance || null,
        secondaryMemberId: claim.secondaryMemberId || null,
        claimId: claim.claimId,
        chargeAmount: claim.chargeAmount,
        claimReceivedDate: claim.claimReceivedDate ? parseDate(claim.claimReceivedDate) : null,
        claimNumber: claim.claimNumber || null,
        claimStatus: claim.claimStatus as any,
        checkNumber: claim.checkNumber || null,
        checkDate: claim.checkDate ? parseDate(claim.checkDate) : null,
        paidAmount: claim.paidAmount || null,
        paymentDate: claim.paidDate ? parseDate(claim.paidDate) : null,
        denialCodes: claim.deniedCode || null,
        denialDate: (claim as any).denialDate ? parseDate((claim as any).denialDate) : null,
        deniedLineItems: claim.deniedLineItems || null,
        denialDescription: claim.denialDescription || null,
        remarks: claim.remarks || null,
        stage: claim.stage as any,
        secondaryClaimNumber: claim.secondaryClaimNumber || null,
        secondaryClaimReceivedDate: claim.secondaryClaimReceivedDate ? parseDate(claim.secondaryClaimReceivedDate) : null,
        secondaryClaimStatus: (claim.secondaryClaimStatus as any) || null,
        secondaryCheckNumber: claim.secondaryCheckNumber || null,
        secondaryCheckDate: claim.secondaryCheckDate ? parseDate(claim.secondaryCheckDate) : null,
        secondaryPaidAmount: claim.secondaryPaidAmount || null,
        secondaryPaymentDate: claim.secondaryPaidDate ? parseDate(claim.secondaryPaidDate) : null,
        secondaryDenialCodes: claim.secondaryDeniedCode || null,
        secondaryDeniedLineItems: claim.secondaryDeniedLineItems || null,
        secondaryDenialDescription: claim.secondaryDenialDescription || null,
        assignedToId: assignedUser.id,
      },
    })
  }

  console.log(`Created ${claimsData.length} claims (3 PAID · 5 DENIED · 2 PARTIALLY-PAID · 3 IN-PROCESS)`)
  console.log('Seeding complete!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
